galleria/galleria/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin

from .views import PublicView

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', PublicView.as_view(), name='public'),

    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='logout'),
    
    url(r'^password-reset/$', 'django.contrib.auth.views.password_reset', {'template_name': 'password_reset.html'}),
    url(r'^password-reset/done/$', 'django.contrib.auth.views.password_reset_done', {'template_name': 'password_reset.html'}, name='password_reset_done'),
    url(r'^password-reset/confirm/$', 'django.contrib.auth.views.password_reset_confirm', {'template_name': 'password_reset.html'}, name='password_reset_done'),
    url(r'^password-reset/complete/$', 'django.contrib.auth.views.password_reset_complete', {'template_name': 'password_reset.html'}, name='password_reset_done'),

    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^markdown/', include( 'django_markdown.urls')),
    url(r'^stocks/', include('stocks.urls')), #Crud demo
    url(r'^categories/', include('categories.urls')), #Crud live demo
    url(r'^artists/', include('artists.urls')), #Crud live demo
    url(r'^contacts/', include('contacts.urls')), #Crud live demo
    url(r'^products/', include('products.urls')), #Crud live demo

    url(r'^', PublicView.as_view(), name='public'), # Catchall and take to front page
)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

galleria/products/urls.py
from django.conf.urls import patterns, url
from products.views import ProductList, ProductCreate, ProductDetail, ProductUpdate, ProductDelete
from products.views import OrderList, OrderCreate, OrderDetail, OrderUpdate, OrderDelete

# The leading / is in the top level pattern which might be like:
#    url(r'^things/', include('yourapp.urls')),

urlpatterns = patterns(
    '',
    url(r'^orders/new/$', OrderCreate.as_view(), name='order_create'),
    url(r'^orders/(?P<pk>\d+)/$', OrderDetail.as_view(), name='order_detail'),
    url(r'^orders/(?P<pk>\d+)/update/$', OrderUpdate.as_view(), name='order_update'),
    url(r'^orders/(?P<pk>\d+)/delete/$', OrderDelete.as_view(), name='order_delete'),
    url(r'^orders/', OrderList.as_view(), name='order_list'),
    url(r'^new/$', ProductCreate.as_view(), name='product_create'),
    url(r'^(?P<pk>\d+)/$', ProductDetail.as_view(), name='product_detail'),
    url(r'^(?P<pk>\d+)/update/$', ProductUpdate.as_view(), name='product_update'),
    url(r'^(?P<pk>\d+)/delete/$', ProductDelete.as_view(), name='product_delete'),
    url(r'^', ProductList.as_view(), name='product_list'),
)

galleria/stocks/urls.py
from django.conf.urls import patterns, url
from stocks.views import StockList, StockCreate, StockDetail, StockUpdate, StockDelete


urlpatterns = patterns(
    '',
    url(r'^new/$', StockCreate.as_view(), name='stock_create'),
    url(r'^(?P<pk>\d+)/$', StockDetail.as_view(), name='stock_detail'),
    url(r'^(?P<pk>\d+)/update/$', StockUpdate.as_view(), name='stock_update'),
    url(r'^(?P<pk>\d+)/delete/$', StockDelete.as_view(), name='stock_delete'),
    url(r'^', StockList.as_view(), name='stock_list'),
)

galleria/products/models.py
from django.core.urlresolvers import reverse
from django.db import models

from model_utils.models import TimeStampedModel

from contacts.models import Contact,Address

class Product(models.Model):
    name = models.CharField(max_length=255)
    COLOUR_CHOICES = (
        ('NR', 'Navy/Red'),
        ('NB', 'Navy/Blue'),
        ('GR', 'Green/Red'),
        ('GB', 'Green/Blue'),
    )
    has_colour = models.BooleanField()
    colour = models.CharField(max_length=2, choices=COLOUR_CHOICES)
    has_size = models.BooleanField()
    size = models.DecimalField(max_digits=5, decimal_places=2,blank=True)
    stock_quantity = models.IntegerField(default=0)
    item_price = models.DecimalField(max_digits=6, decimal_places=2)
    initials_price = models.DecimalField(max_digits=6, decimal_places=2)

    def __str__(self):
        if self.has_colour and self.has_size:
            return('{} {} {}"'.format(self.name,self.get_colour_display(),self.size))
        elif (not self.has_colour) and self.has_size:
            return('{} {}"'.format(self.name,self.size))
        elif self.has_colour and not self.has_size:
            return('{} {}'.format(self.name,self.get_colour_display()))
        else:
            return('{}'.format(self.name))

    def _get_description(self):
        "Returns a short description of the product."
        return('{}'.format(self.__str__()))
    description = property(_get_description)


    def __repr__(self):
        return self.__str__()

    def get_absolute_url(self):
        return reverse('product_detail', args=[str(self.id)])


class Order(TimeStampedModel):
    reference = models.CharField(max_length=255)
    delivery_note = models.CharField(max_length=255)
    comment = models.CharField(max_length=255, blank=True,default='')
    comment = models.CharField(max_length=255, blank=True,default='')
    ORDER_STATES = (
        ('EN', 'Entered'),
        ('PR', 'Processed'),
        ('DI', 'Dispatched'),
        ('CA', 'Cancelled'),
        ('RE', 'Returned'),
    )
    state = models.CharField(max_length=2, choices=ORDER_STATES)
    contact = models.ForeignKey(Contact)
    invoice_address = models.ForeignKey(Address, related_name="invoices", null=True, default=None)
    delivery_address = models.ForeignKey(Address, default=None, blank=True, related_name="deliveries", null=True)

    def __str__(self):
        return '{} {} ({})'.format(self.reference, self.contact, self.id )

    def _get_description(self):
        "Returns a short description of the product."
        return('{}'.format(self.__str__()))
    description = property(_get_description)


    def __repr__(self):
        return self.__str__()

    def get_absolute_url(self):
        return reverse('order_detail', args=[str(self.id)])


class OrderItem(models.Model):
    product = models.ForeignKey('Product')
    order = models.ForeignKey('Order')
    initial = models.CharField(max_length=50,blank=True)
    qty = models.IntegerField(default=1)
    item_price = models.DecimalField(max_digits=6, decimal_places=2)

    def _get_total_price(self):
        "Returns a short description of the product."
        return(self.qty*self.item_price)
    total_price = property(_get_total_price)

galleria/products/forms.py
from django.forms import ModelForm

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from products.models import Product,Order


class ProductForm(ModelForm):
    def __init__(self, *args, **kwargs):
          super(ProductForm, self).__init__(*args, **kwargs)
          self.helper = FormHelper(self)
          self.helper.form_method = 'post'
          self.helper.form_action = '.'
          self.helper.label_class = 'col-lg-2'
          self.helper.field_class = 'col-lg-8'
          self.helper.form_class = 'form-horizontal'
          self.helper.add_input(Submit('submit', 'Submit'))
        
    class Meta:
        model = Product

class OrderForm(ModelForm):
    def __init__(self, *args, **kwargs):
          super(OrderForm, self).__init__(*args, **kwargs)
          self.helper = FormHelper(self)
          self.helper.form_method = 'post'
          self.helper.form_action = '.'
          self.helper.label_class = 'col-lg-2'
          self.helper.field_class = 'col-lg-8'
          self.helper.form_class = 'form-horizontal'
          self.helper.add_input(Submit('submit', 'Submit'))

    class Meta:
        model = Order

galleria/products/views.py
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.core.urlresolvers import reverse
from vanilla import ListView, CreateView, DetailView, UpdateView, DeleteView
from .forms import ProductForm, OrderForm
from .models import Product, Order


class ProductCRUDView(object):
    model = Product
    form_class = ProductForm
    paginate_by = 20

    def get_success_url(self):
        return reverse('product_list')

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ProductCRUDView, self).dispatch(*args, **kwargs)


class ProductList(ProductCRUDView, ListView):
    pass


class ProductCreate(ProductCRUDView, CreateView):
    pass


class ProductDetail(ProductCRUDView, DetailView):
    pass


class ProductUpdate(ProductCRUDView, UpdateView):
    pass


class ProductDelete(ProductCRUDView, DeleteView):
    pass


class OrderCRUDView(object):
    model = Order
    form_class = OrderForm
    paginate_by = 20

    def get_success_url(self):
        return reverse('order_list')

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(OrderCRUDView, self).dispatch(*args, **kwargs)


class OrderList(OrderCRUDView, ListView):
    pass


class OrderCreate(OrderCRUDView, CreateView):
    pass


class OrderDetail(OrderCRUDView, DetailView):
    pass


class OrderUpdate(OrderCRUDView, UpdateView):
    pass


class OrderDelete(OrderCRUDView, DeleteView):
    pass

galleria/products/templates/products/order_detail.html
{% extends "orders_base.html" %}
{% block title %}Order{% endblock %}

{% block content %}
<h1><em>Detail:</em> {{ object.description }}</h1>
<p><em> Client = </em>{{ object.contact }}</p>
<p><em> Invoice address = </em>{{ object.invoice_address }}</p>
<p><em> Delivery address = </em>{{ object.delivery_address }}</p>
<table class="table table-striped">
    <thead>
    <tr>
        <th>Description</th>
        <th>Colour</th>
        <th>Size</th>
        <th>Amount</th>
        <th>Initials or Date</th>
        <th>Price per Item</th>
        <th>Price for Initials</th>
        <th>Total</th>
    </tr>
    </thead>
    <tbody>
    {% for item in object.orderitem_set.all %}
    <tr>
        <td>{{ item.product.name }}</td>
        <td>{{ item.product.colour }}</td>
        <td>{{ item.product.size }}</td>
        <td>{{ item.qty }}</td>
        <td>{{ item.initials }}</td>
        <td>{{ item.item_price }}</td>
        <td>{{ item.intials_price }}</td>
        <td>{{ item.total_price }}</td>
    </tr>
    {% empty %}
    <td colspan="8">No orders.</td>
    {% endfor %}
    <tr>
        <td colspan="7">P&P</td>
        <td>{{ object.post_charges }}</td>
    </tr>
    <tr>
        <td colspan="7">Total</td>
        <td>{{ object.total_price }}</td>
    </tr>
    </tbody>
</table>
<div class="row">
    <div class="col-md-6">
        <h2> POST AND PACKAGING CHARGES </h2>
        <p> </p>
        <table class="table">
            <thead>
            <tr>
                <td>Item Value</td>
                <td>Charge P&amp;P</td>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>up to £50.00</td>
                <td>£ 5.00</td>
            </tr>
            <tr>
                <td>over £50.00 &amp; below £200.00</td>
                <td>£ 7.00</td>
            </tr>
            <tr>
                <td>over £200.00</td>
                <td>£10.00 </td>
            </tr>
            </tbody>
        </table>
        <p> </p>
        <table class="table">
            <tbody>
            <tr>
                <td>Please make payment to:</td>
                <td>THE ENGLISH ROOM</td>
            </tr>
            <tr>
                <td>BANK TRANSFER:</td>
                <td>SORT CODE  60 04 04    	ACC. NO.  85117331</td>
            </tr>
            </tbody>
        </table>

    </div>
</div>
<a class="btn btn-info btn-md" href="{% url 'order_list' %}">List</a>
{% endblock %}

galleria/products/templates/products/order_form.html
{% extends "orders_base.html" %}
{% block title %}Order{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
    <h1>{% if object %}Update{% else %}Create{% endif %}</h1>
    {% crispy form %}
{% endblock %}

galleria/products/templates/products/order_list.html
{% extends "orders_base.html" %}
{% block title %}Order{% endblock %}

{% block content %}
    <h1>Order Listing</h1>
    <a class="btn btn-primary" href="{% url 'order_create' %}">Create</a>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Ref</th>
          <th>Description</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        {% for object in object_list %}
            <tr>
                <td>{{ object.reference }}</td>
                <td>{{ object.description }}</td>
                <td>
                    <a class="btn btn-info btn-xs" href="{% url 'order_detail' object.pk %}">Details</a>
                    <a class="btn btn-warning btn-xs" href="{% url 'order_update' object.pk %}">Update</a>
                </td>
            </tr>
        {% empty %}
                <td colspan="3">No orders.</td>
        {% endfor %}
      </tbody>
    </table>

    {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{% url 'product_list' %}?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="{% url 'product_list' %}?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
    {% endif %}


{% endblock %}

galleria/products/templates/products/product_confirm_delete.html
{% extends "products_base.html" %}
{% block title %}Delete Product{% endblock %}

{% block content %}
    <h1>Delete</h1>
    <p>Are you sure you want to delete?</p>

    <form id="product_form" method="post" action=".">
    {% csrf_token %}
    <input type="submit" value="Yes" class="btn btn-primary" /> <a href="{% url 'product_list' %}" class="btn btn-danger">No</a>
    </form>
{% endblock %}

galleria/products/templates/products/product_detail.html
{% extends "products_base.html" %}
{% block title %}Product{% endblock %}

{% block content %}
    <h1>Detail {{ object.description }}</h1>
    <p><em> Description = </em>{{ object.name }}</p>
    {% if object.has_colour %}
      <p><em> Colour = </em>{{ object.colour }}</p>
    {% endif %}
    {% if object.has_size %}
      <p><em> Size = </em>{{ object.size }}</p>
    {% endif %}
    <p><em> Stock = </em>{{ object.size }}</p>
    <p><em> Price = </em>{{ object.item_price }}</p>
    <p><em> Price of initials = </em>{{ object.initials_price }}</p>
    <a href="{% url 'product_list' %}">List</a>
{% endblock %}

galleria/products/templates/products/product_form.html
{% extends "products_base.html" %}
{% block title %}product{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
    <h1>{% if object %}Update{% else %}Create{% endif %}</h1>
    {% crispy form %}
{% endblock %}

galleria/products/templates/products/product_list.html
{% extends "products_base.html" %}
{% block title %}product{% endblock %}

{% block content %}
    <h1>Product Listing</h1>
    <a class="btn btn-primary" href="{% url 'product_create' %}">Create</a>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>ID</th>
          <th>Description</th>
          <th>Stock</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        {% for object in object_list %}
            <tr>
                <td>{{ object.id }}</td>
                <td>{{ object.description }}</td>
                <td>{{ object.stock_quantity }}</td>
                <td>
                    <a class="btn btn-info btn-xs" href="{% url 'product_detail' object.pk %}">Details</a> 
                    <a class="btn btn-warning btn-xs" href="{% url 'product_update' object.pk %}">Update</a> 
                </td>
            </tr>
        {% empty %}
                <td colspan="3">No items.</td>
        {% endfor %}
      </tbody>
    </table>

    {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{% url 'product_list' %}?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="{% url 'product_list' %}?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
    {% endif %}


{% endblock %}